import Foundation

/// Tłumaczy teksty interfejsu. Źródłem są teksty polskie (język bazowy aplikacji), więc dla języka
/// polskiego funkcja zwraca tekst bez zmian. Dla pozostałych języków szuka angielskiego odpowiednika:
/// najpierw dokładnego, potem według wzorca z wstawkami (np. "Dodano listę {}").
/// Wymuszenie języka: `defaults write com.italiano88.MacAdBlock appLanguage en` (albo `pl`).
func L(_ text: String) -> String {
    Localizer.shared.translate(text)
}

final class Localizer: @unchecked Sendable {
    static let shared = Localizer()

    private let usesEnglish: Bool
    private let lock = NSLock()
    private var cache: [String: String] = [:]
    private let patterns: [(NSRegularExpression, String)]

    private init() {
        let forced = UserDefaults.standard.string(forKey: "appLanguage")
        let preferred = forced ?? Locale.preferredLanguages.first ?? "pl"
        usesEnglish = !preferred.lowercased().hasPrefix("pl")
        patterns = Self.patternSource.compactMap { source, template in
            (try? NSRegularExpression(pattern: source)).map { ($0, template) }
        }
    }

    func translate(_ text: String) -> String {
        guard usesEnglish, !text.isEmpty else { return text }
        if let exact = Self.exact[text] { return exact }
        lock.lock()
        if let cached = cache[text] {
            lock.unlock()
            return cached
        }
        lock.unlock()

        var result = text
        let range = NSRange(text.startIndex..., in: text)
        for (expression, template) in patterns {
            guard let match = expression.firstMatch(in: text, range: range) else { continue }
            var output = template
            // Wstawki tłumaczymy osobno: mogą być komunikatem błędu albo nazwą listy.
            for group in stride(from: match.numberOfRanges - 1, through: 1, by: -1) {
                guard let groupRange = Range(match.range(at: group), in: text) else { continue }
                output = output.replacingOccurrences(of: "$\(group)", with: translate(String(text[groupRange])))
            }
            result = output
            break
        }
        lock.lock()
        cache[text] = result
        lock.unlock()
        return result
    }

    private static let patternSource: [(String, String)] = [
        ("^Aktywny · (.+?) reguł$", "Active · $1 rules"),
        ("^Zachowaj ustawienia\\? Firewall wyłączy się za (.+?) s\\.$", "Keep these settings? The firewall will turn off in $1 s."),
        ("^Okres próbny: pozostało (.+?) dni$", "Trial period: $1 days left"),
        ("^Razem: (.+?)$", "Total: $1"),
        ("^Subskrybuj za (.+?) / miesiąc$", "Subscribe for $1 / month"),
        ("^Subskrypcja: (.+?)$", "Subscription: $1"),
        ("^Wstrzymana do (.+?)$", "Paused until $1"),
        ("^Nie udało się odświeżyć DNS: (.+?)$", "Could not flush DNS: $1"),
        ("^Na\\ pozostałych\\ sieciach\\ Wi‑Fi\\ oraz\\ Ethernet\\ VPN\\ połączy\\ się\\ automatycznie\\.\\ Rozpoznano\\ (.+?)\\ zaufanych\\ sieci\\.$", "On all other Wi‑Fi and Ethernet networks the VPN connects automatically. $1 trusted networks recognized."),
        ("^Trzy\\ kolejne\\ próby\\ nie\\ powiodły\\ się\\.\\ Ochrona\\ działa\\ na\\ wcześniej\\ pobranych\\ regułach\\.\\ (.+?)$", "Three attempts in a row failed. Protection keeps using previously downloaded rules. $1"),
        ("^Nie\\ udało\\ się\\ zaktualizować\\ MacAdBlock\\ w\\ folderze\\ Aplikacje\\.\\ (.+?)$", "Could not update MacAdBlock in Applications. $1"),
        ("^Lista\\ ma\\ (.+?)\\ domen,\\ ale\\ sekcja\\ MacAdBlock\\ nie\\ jest\\ aktywna\\.$", "The list has $1 domains, but the MacAdBlock section is not active."),
        ("^W\\ /etc/hosts\\ działa\\ komplet\\ (.+?)\\ domen\\ z\\ najnowszej\\ listy\\.$", "All $1 domains from the latest list are active in /etc/hosts."),
        ("^W\\ /etc/hosts\\ jest\\ (.+?)\\ z\\ (.+?)\\ domen\\.\\ Zastosuj\\ najnowszą\\ listę\\.$", "/etc/hosts contains $1 of $2 domains. Apply the latest list."),
        ("^Safari\\ odrzuciło\\ listę\\ —\\ zmniejszam\\ limit\\ do\\ (.+?)\\ reguł$", "Safari rejected the list — lowering the limit to $1 rules"),
        ("^Nie\\ udało\\ się\\ uzyskać\\ uprawnień\\ administratora:\\ (.+?)$", "Could not obtain administrator privileges: $1"),
        ("^Rozszerzenia\\ Safari\\ nie\\ są\\ jeszcze\\ gotowe\\.\\ (.+?)$", "Safari extensions are not ready yet. $1"),
        ("^Helper\\ hosts\\ nie\\ może\\ zostać\\ uruchomiony\\.\\ (.+?)$", "The hosts helper cannot be started. $1"),
        ("^Nie\\ udało\\ się\\ zapisać\\ własnych\\ ustawień:\\ (.+?)$", "Could not save custom settings: $1"),
        ("^To\\ nie\\ wygląda\\ na\\ poprawną\\ nazwę\\ domeny:\\ (.+?)$", "This doesn't look like a valid domain name: $1"),
        ("^Nie\\ udało\\ się\\ odczytać\\ stanu\\ helpera:\\ (.+?)$", "Could not read the helper state: $1"),
        ("^System\\ nie\\ mógł\\ skopiować\\ aplikacji:\\ (.+?)$", "The system could not copy the app: $1"),
        ("^Nie\\ udało\\ się\\ zapisać\\ konfiguracji:\\ (.+?)$", "Could not save the configuration: $1"),
        ("^Nie\\ udało\\ się\\ wczytać\\ konfiguracji:\\ (.+?)$", "Could not load the configuration: $1"),
        ("^ditto\\ zakończyło\\ działanie\\ z\\ kodem\\ (.+?)\\.$", "ditto exited with code $1."),
        ("^Pęk\\ kluczy\\ odrzucił\\ operację\\ \\(kod\\ (.+?)\\)\\.$", "The Keychain rejected the operation (code $1)."),
        ("^Żadna\\ włączona\\ reguła\\ nie\\ dotyczy\\ (.+?)$", "No enabled rule applies to $1"),
        ("^Nie\\ udało\\ się\\ naprawić\\ helpera:\\ (.+?)$", "Could not repair the helper: $1"),
        ("^Safari\\ nie\\ przeładowało\\ reguł\\.\\ (.+?)$", "Safari did not reload the rules. $1"),
        ("^Instalator\\ wersji\\ (.+?)\\ jest\\ gotowy$", "The installer for version $1 is ready"),
        ("^Żadna\\ z\\ (.+?)\\ sprawdzonych\\ list$", "None of the $1 lists checked"),
        ("^Zaktualizowano\\ z\\ (.+?)\\ błędami$", "Updated with $1 errors"),
        ("^(.+?)\\ z\\ (.+?)\\ źródeł\\ jest\\ aktywnych$", "$1 of $2 sources are active"),
        ("^Dostępna\\ jest\\ wersja\\ (.+?)$", "Version $1 is available"),
        ("^około\\ (.+?)\\ reguł\\ i\\ domen$", "about $1 rules and domains"),
        ("^Pobieranie\\ wersji\\ (.+?)…$", "Downloading version $1…"),
        ("^(.+?)\\ aktywnych\\ źródeł$", "$1 active sources"),
        ("^Dostępna\\ wersja\\ (.+?)$", "Version $1 available"),
        ("^(.+?)\\ ·\\ około\\ (.+?)\\ wpisów$", "$1 · about $2 entries"),
        ("^Usunięto\\ listę\\ (.+?)$", "Removed list $1"),
        ("^Ochrona\\ dotyka\\ (.+?)$", "Protection affects $1"),
        ("^Zastosuj\\ (.+?)\\ domen$", "Apply $1 domains"),
        ("^(.+?)\\ list\\ ·\\ (.+?)\\ reguł$", "$1 lists · $2 rules"),
        ("^Dodano\\ listę\\ (.+?)$", "Added list $1"),
        ("^(.+?)\\ aktywnych$", "$1 active"),
        ("^(.+?)\\ źródeł$", "$1 sources"),
        ("^(.+?)\\ list$", "$1 lists"),
    ]

    private static let exact: [String: String] = [
        "Adres, blok CIDR lub domena (puste = dowolny)": "Address, CIDR block or domain (empty = any)",
        "Blokuj": "Block",
        "Blokuj połączenia po adresie, porcie i protokole. Reguły działają w całym systemie (pf).": "Block connections by address, port and protocol. Rules apply system-wide (pf).",
        "Blokuj połączenia przychodzące": "Block incoming connections",
        "Brak reguł. Dodaj pierwszą poniżej.": "No rules yet. Add the first one below.",
        "Dla ruchu przychodzącego adres to źródło, a port to port na Twoim Macu. Zezwolenia mają pierwszeństwo przed blokadami.": "For incoming traffic the address is the source and the port is the port on your Mac. Allow rules take precedence over block rules.",
        "Dodaj regułę": "Add rule",
        "Dowolny protokół": "Any protocol",
        "Firewall": "Firewall",
        "Firewall MacAdBlock": "MacAdBlock firewall",
        "Firewall macOS": "macOS firewall",
        "Firewall został wyłączony.": "The firewall has been turned off.",
        "Firewall został zastosowany.": "The firewall has been applied.",
        "Jeśli po zmianie stracisz dostęp do sieci, nic nie rób — MacAdBlock sam cofnie firewall.": "If you lose network access after the change, do nothing — MacAdBlock will revert the firewall on its own.",
        "Nie potwierdzono ustawień — firewall został wyłączony.": "Settings were not confirmed — the firewall has been turned off.",
        "Nie udało się odczytać stanu firewalla macOS.": "Could not read the state of the macOS firewall.",
        "Nieprawidłowy adres lub domena.": "Invalid address or domain.",
        "Nieprawidłowy port. Wpisz np. 443 albo 8000:8100.": "Invalid port. Enter e.g. 443 or 8000:8100.",
        "Notatka (opcjonalnie)": "Note (optional)",
        "Nowa reguła": "New rule",
        "Odrzuca nowe połączenia z sieci do Twojego Maca. Odpowiedzi na Twoje własne połączenia przechodzą. Może przeszkadzać w AirDrop i udostępnianiu.": "Rejects new connections from the network to your Mac. Replies to your own connections still get through. May interfere with AirDrop and sharing.",
        "Osiągnięto limit reguł.": "Rule limit reached.",
        "Port, np. 443": "Port, e.g. 443",
        "Przychodzące": "Incoming",
        "Pytanie „Czy zezwolić tej aplikacji na połączenie?” wymaga rozszerzenia sieciowego Content Filter, które Apple udostępnia tylko płatnemu kontu Developer. Na koncie Personal Team ta funkcja nie jest dostępna.": "Asking “Allow this app to connect?” requires a Content Filter network extension, which Apple provides only to paid Developer accounts. This feature is not available on a Personal Team account.",
        "Reguły": "Rules",
        "Reguły dla aplikacji": "Per-app rules",
        "Reguły przestają działać po restarcie Maca; MacAdBlock przywraca je przy starcie aplikacji.": "Rules stop working after a Mac restart; MacAdBlock restores them when the app starts.",
        "Ruch wychodzący tylko na DNS, DHCP, NTP oraz HTTP i HTTPS. Reszta (np. poczta, SSH, gry) jest blokowana.": "Outgoing traffic only to DNS, DHCP, NTP and HTTP/HTTPS. Everything else (e.g. mail, SSH, games) is blocked.",
        "Tryb blokady": "Lockdown mode",
        "Tryb ukrycia (nie odpowiadaj na ping i skanowanie)": "Stealth mode (do not respond to ping and scans)",
        "Ustawienia firewalla zostały zachowane.": "Firewall settings have been kept.",
        "Usuń regułę": "Delete rule",
        "Wbudowany firewall systemu filtruje połączenia przychodzące dla poszczególnych aplikacji. Zmiana wymaga uprawnień administratora.": "The built-in system firewall filters incoming connections per application. Changing it requires administrator privileges.",
        "Wychodzące": "Outgoing",
        "Włącz firewall macOS": "Turn on macOS firewall",
        "Włączony, ale reguły nie są wczytane": "Enabled, but the rules are not loaded",
        "Zachowaj": "Keep",
        "Zastosuj zmiany": "Apply changes",
        "Zmiany nie zostały jeszcze zastosowane.": "Changes have not been applied yet.",
        "Zmieniono ustawienia firewalla macOS.": "The macOS firewall settings were changed.",
        "dowolny adres": "any address",
        "dowolny protokół": "any protocol",
        "przychodzące": "incoming",
        "wychodzące": "outgoing",
        "Wersja MacAdBlock i aktualizacje": "MacAdBlock version and updates",
        "Sprawdzanie…": "Checking…",
        "Sprawdź aktualizacje": "Check for updates",
        "Sprawdzanie aktualizacji…": "Checking for updates…",
        "Aktualne": "Up to date",
        "domen": "domains",
        "Elementy": "Elements",
        "Kreator": "Wizard",
        "Dodaj": "Add",
        "Ustawienia…": "Settings…",
        "Codziennie": "Daily",
        "Instrukcja": "Instructions",
        "Automatyczne aktualizacje list filtrów": "Automatic filter list updates",
        "Blokowanie reklam i trackerów w Safari": "Ad and tracker blocking in Safari",
        "Brak danych. Liczby pojawią się, gdy filtrowanie DNS zablokuje pierwsze żądania.": "No data yet. Numbers will appear once DNS filtering blocks its first requests.",
        "Dziennik blokad, pauza i wyjątki": "Block log, pause and exceptions",
        "Dzień": "Day",
        "Dziękujemy za wsparcie!": "Thank you for your support!",
        "Dziękujemy! Subskrypcja jest aktywna.": "Thank you! Your subscription is active.",
        "Limit domen w /etc/hosts": "Domain limit in /etc/hosts",
        "Mniejszy plik hosts przyspiesza rozwiązywanie nazw. Zmiana obowiązuje po ponownym kliknięciu „Zastosuj”.": "A smaller hosts file speeds up name resolution. The change takes effect after you click “Apply” again.",
        "Najczęściej blokowane domeny": "Most blocked domains",
        "Nie udało się zweryfikować zakupu.": "The purchase could not be verified.",
        "Nie znaleziono aktywnej subskrypcji.": "No active subscription was found.",
        "Ochrona systemowa przez /etc/hosts i DNS": "System-wide protection via /etc/hosts and DNS",
        "Okres próbny się zakończył": "The trial period has ended",
        "Podpis MacAdBlock wkrótce wygaśnie": "The MacAdBlock signature is about to expire",
        "Podpis wygasł. Zbuduj aplikację ponownie w Xcode, aby rozszerzenia Safari znów działały.": "The signature has expired. Rebuild the app in Xcode so the Safari extensions work again.",
        "Zbuduj aplikację ponownie w Xcode w ciągu 2 dni, aby rozszerzenia Safari nie przestały działać.": "Rebuild the app in Xcode within 2 days so the Safari extensions keep working.",
        "Przywrócono subskrypcję.": "Subscription restored.",
        "Przywróć zakupy": "Restore purchases",
        "Subskrypcja aktywna": "Subscription active",
        "Subskrypcja jest chwilowo niedostępna. Sprawdź połączenie z internetem i spróbuj ponownie.": "The subscription is temporarily unavailable. Check your internet connection and try again.",
        "Subskrypcja odnawia się co miesiąc, dopóki jej nie anulujesz w ustawieniach konta Apple.": "The subscription renews monthly until you cancel it in your Apple account settings.",
        "Subskrypcja…": "Subscription…",
        "Wstrzymaj do jutra": "Pause until tomorrow",
        "Wstrzymaj na 1 godzinę": "Pause for 1 hour",
        "Wstrzymaj na 5 minut": "Pause for 5 minutes",
        "Wznów ochronę teraz": "Resume protection now",
        "Zablokowane żądania DNS": "Blocked DNS requests",
        "Zakup czeka na zatwierdzenie.": "The purchase is awaiting approval.",
        "Zamknij": "Close",
        "7 dni": "7 days",
        "30 dni": "30 days",
        "Odśwież DNS": "Flush DNS",
        "Czyści pamięć podręczną DNS, żeby zmiany w hosts zadziałały od razu.": "Clears the DNS cache so hosts changes take effect immediately.",
        "Pamięć podręczna DNS została odświeżona": "DNS cache flushed",
        "Nie sprawdzano": "Not checked yet",
        "Oba rozszerzenia działają": "Both extensions are working",
        "Włącz oba rozszerzenia": "Enable both extensions",
        "Włącz Web Extension": "Enable Web Extension",
        "Włącz Content Blocker": "Enable Content Blocker",
        "Sprawdzanie rozszerzeń…": "Checking extensions…",
        "Pakiet jest poprawnie zainstalowany i podpisany": "The package is installed and signed correctly",
        "MacAdBlock nie może utworzyć żadnego katalogu roboczego.": "MacAdBlock cannot create a working directory.",
        "Dodano wyjątek — przebudowuję reguły": "Exception added — rebuilding rules",
        "Usunięto wyjątek — przebudowuję reguły": "Exception removed — rebuilding rules",
        "Zapisano własne reguły": "Custom rules saved",
        "Podaj nazwę i poprawny adres HTTPS listy.": "Enter a name and a valid HTTPS address for the list.",
        "Ta lista jest już dodana.": "This list has already been added.",
        "Zmieniono wyjątki w Safari — przebudowuję reguły": "Exceptions changed in Safari — rebuilding rules",
        "Konfiguracja została zapisana": "Configuration saved",
        "Konfiguracja została wczytana": "Configuration loaded",
        "Statystyki zostały wyczyszczone": "Statistics cleared",
        "MacAdBlock jest już zainstalowany": "MacAdBlock is already installed",
        "W folderze Aplikacje znajduje się ta sama lub nowsza wersja. Uruchom zainstalowaną kopię, aby działały rozszerzenia Safari i ochrona hosts.": "The Applications folder already contains the same or a newer version. Run the installed copy so the Safari extensions and hosts protection work.",
        "Uruchom z Aplikacji": "Open from Applications",
        "Zainstaluj MacAdBlock": "Install MacAdBlock",
        "Zaktualizuj MacAdBlock": "Update MacAdBlock",
        "MacAdBlock zostanie automatycznie skopiowany do systemowego folderu Aplikacje. macOS poprosi o hasło administratora. Instalacja zachowa ustawienia i umożliwi rejestrację rozszerzeń oraz helpera.": "MacAdBlock will be copied to the system Applications folder automatically. macOS will ask for an administrator password. Your settings are kept, and the extensions and helper can then be registered.",
        "Zainstaluj automatycznie": "Install automatically",
        "Zaktualizuj automatycznie": "Update automatically",
        "Wymaga instalacji w /Applications": "Must be installed in /Applications",
        "Automatyczne aktualizacje czekają na adres manifestu": "Automatic updates are waiting for a manifest address",
        "Nowsza wersja MacAdBlock jest gotowa do pobrania i instalacji.": "A newer version of MacAdBlock is ready to download and install.",
        "Pobierz i zainstaluj": "Download and install",
        "MacAdBlock jest aktualny": "MacAdBlock is up to date",
        "Nie udało się sprawdzić aktualizacji": "Could not check for updates",
        "Instalowanie MacAdBlock w folderze Aplikacje…": "Installing MacAdBlock in Applications…",
        "MacAdBlock został zainstalowany": "MacAdBlock has been installed",
        "Instalacja anulowana": "Installation cancelled",
        "Instalacja nie powiodła się": "Installation failed",
        "Aktualizacja nie powiodła się": "Update failed",
        "Ochrona jest wyłączona": "Protection is off",
        "Ochrona jest wyłączona — włącz ją, aby aktualizować listy": "Protection is off — turn it on to update lists",
        "Pobieranie i kompilowanie list…": "Downloading and compiling lists…",
        "Listy są aktualne": "Lists are up to date",
        "Listy i ochrona hosts są aktualne": "Lists and hosts protection are up to date",
        "MacAdBlock nie może zaktualizować list": "MacAdBlock cannot update the lists",
        "Ochrona hosts wymaga uruchomienia MacAdBlock z folderu Aplikacje i aktywnego helpera.": "Hosts protection requires running MacAdBlock from the Applications folder with an active helper.",
        "Ochrona hosts jest aktywna": "Hosts protection is active",
        "Usunięcie sekcji hosts wymaga uruchomienia MacAdBlock z folderu Aplikacje i aktywnego helpera.": "Removing the hosts section requires running MacAdBlock from the Applications folder with an active helper.",
        "Sekcja hosts została usunięta": "Hosts section removed",
        "Nie udało się zarejestrować helpera. Sprawdź podpis aplikacji i zatwierdź usługę w Rzeczach logowania.": "Could not register the helper. Check the app signature and approve the service in Login Items.",
        "Tryb lokalny jest gotowy. Przy zmianie /etc/hosts macOS poprosi o hasło administratora.": "Local mode is ready. macOS will ask for an administrator password when /etc/hosts changes.",
        "Helper jest gotowy. Sekcja hosts będzie odświeżana razem z filtrami.": "The helper is ready. The hosts section will be refreshed along with the filters.",
        "macOS wymaga jednorazowego zatwierdzenia helpera w Rzeczach logowania.": "macOS needs a one-time approval of the helper in Login Items.",
        "Helper nie został znaleziony w pakiecie aplikacji.": "The helper was not found in the app bundle.",
        "Helper nie jest jeszcze zarejestrowany.": "The helper is not registered yet.",
        "Nieznany stan helpera.": "Unknown helper state.",
        "macOS wymaga ponownego zatwierdzenia helpera w Rzeczach logowania.": "macOS needs you to approve the helper again in Login Items.",
        "Helper został ponownie zarejestrowany.": "The helper was registered again.",
        "Rozszerzenia Safari działają": "Safari extensions are working",
        "Przenieś MacAdBlock do systemowego folderu Aplikacje (/Applications) i uruchom tę kopię.": "Move MacAdBlock to the system Applications folder (/Applications) and run that copy.",
        "Podpis tej kopii MacAdBlock jest nieważny lub niezaufany. W Xcode wybierz swój Team w Signing & Capabilities, przebuduj aplikację i zainstaluj ją ponownie.": "This copy of MacAdBlock has an invalid or untrusted signature. In Xcode choose your Team under Signing & Capabilities, rebuild the app and install it again.",
        "W pakiecie aplikacji brakuje helpera hosts. Zbuduj cały schemat MacAdBlock, nie sam target aplikacji.": "The hosts helper is missing from the app bundle. Build the whole MacAdBlock scheme, not just the app target.",
        "W pakiecie brakuje rozszerzeń Safari. Zbuduj cały schemat MacAdBlock i zainstaluj aplikację ponownie.": "The Safari extensions are missing from the bundle. Build the whole MacAdBlock scheme and reinstall the app.",
        "Ta kopia jest podpisana lokalnie bez Apple Team ID, dlatego Safari ukrywa oba rozszerzenia. Zaloguj Apple ID w Xcode i podpisz targety MacAdBlock, SafariBlocker oraz SafariWebExtension tym samym Teamem. Do krótkiego testu możesz też włączyć w Safari opcję Programowanie → Zezwalaj na niepodpisane rozszerzenia; Safari wyłącza ją po każdym zamknięciu.": "This copy is signed locally without an Apple Team ID, so Safari hides both extensions. Sign in with your Apple ID in Xcode and sign the MacAdBlock, SafariBlocker and SafariWebExtension targets with the same Team. For a quick test you can also enable Develop → Allow Unsigned Extensions in Safari; Safari turns it off every time it quits.",
        "Safari nie może zarejestrować rozszerzeń z tej lokalizacji. Przenieś MacAdBlock do systemowego folderu Aplikacje (/Applications), uruchom go ponownie, a następnie w Safari wybierz Ustawienia → Rozszerzenia.": "Safari cannot register extensions from this location. Move MacAdBlock to the system Applications folder (/Applications), run it again, then choose Settings → Extensions in Safari.",
        "Rozszerzenia są w aplikacji, ale Safari ich nie pokazuje, ponieważ ta kopia nie ma podpisu Apple Team ID. Zaloguj Apple ID w Xcode i podpisz MacAdBlock oraz oba rozszerzenia tym samym Teamem. Safari nie pozwala aplikacji samodzielnie ominąć tego zabezpieczenia ani włączyć rozszerzeń bez Twojej zgody.": "The extensions are in the app, but Safari doesn't show them because this copy has no Apple Team ID signature. Sign in with your Apple ID in Xcode and sign MacAdBlock and both extensions with the same Team. Safari doesn't let an app bypass this safeguard or turn extensions on without your consent.",
        "Safari nie odnalazło rozszerzeń MacAdBlock. Otwórz Safari → Ustawienia → Rozszerzenia i zaznacz MacAdBlock Content Blocker oraz MacAdBlock Web Extension. Apple wymaga tej jednorazowej zgody użytkownika. Jeśli rozszerzeń nie ma, uruchom ponownie MacAdBlock z folderu Aplikacje.": "Safari didn't find the MacAdBlock extensions. Open Safari → Settings → Extensions and tick MacAdBlock Content Blocker and MacAdBlock Web Extension. Apple requires this one-time consent from the user. If the extensions aren't listed, relaunch MacAdBlock from the Applications folder.",
        "Listy gotowe — dokończ konfigurację podpisu i rozszerzeń Safari": "Lists ready — finish setting up signing and the Safari extensions",
        "Listy zaktualizowane — włącz rozszerzenia MacAdBlock w Safari": "Lists updated — enable the MacAdBlock extensions in Safari",
        "Reguły Safari zostały przeładowane": "Safari rules reloaded",
        "Podstawowe reklamy i śledzenie": "Basic ads and tracking",
        "Reklamy, prywatność i bezpieczne hosts": "Ads, privacy and safe hosts",
        "Najwięcej list; może wymagać wyjątków": "Most lists; may need exceptions",
        "Gotowy": "Ready",
        "Lekka": "Light",
        "Zalecana": "Recommended",
        "Maksymalna": "Maximum",
        "Aktualizacje muszą być pobierane przez bezpieczne połączenie HTTPS.": "Updates must be downloaded over a secure HTTPS connection.",
        "Serwer aktualizacji zwrócił nieprawidłową odpowiedź.": "The update server returned an invalid response.",
        "Manifest aktualizacji jest nieprawidłowy.": "The update manifest is invalid.",
        "Pobrany instalator nie przeszedł kontroli integralności SHA-256.": "The downloaded installer failed the SHA-256 integrity check.",
        "Pakiet aktualizacji nie ma ważnego podpisu tego samego wydawcy.": "The update package doesn't have a valid signature from the same publisher.",
        "Pakiet aktualizacji przekracza dozwolony rozmiar.": "The update package exceeds the allowed size.",
        "Skopiowana aplikacja jest niekompletna albo ma nieprawidłową wersję.": "The copied app is incomplete or has the wrong version.",
        "Instalacja została anulowana.": "Installation was cancelled.",
        "Nie udało się usunąć metadanych Finder z kopii aplikacji.": "Could not remove Finder metadata from the app copy.",
        "System odrzucił operację instalacji.": "The system rejected the installation.",
        "Uruchomiona wersja MacAdBlock": "Running version of MacAdBlock",
        "Później": "Later",
        "Ochrona systemowa": "System protection",
        "Aktywność": "Activity",
        "Prywatny tunel": "Private tunnel",
        "Systemowy VPN IKEv2 z bezpiecznym przechowywaniem danych": "System IKEv2 VPN with secure credential storage",
        "Najpierw skonfiguruj serwer i konto": "Set up the server and account first",
        "Czas połączenia": "Connection time",
        "Rozłącz": "Disconnect",
        "Połącz": "Connect",
        "Ustawienia VPN": "VPN settings",
        "Skonfiguruj VPN": "Set up VPN",
        "Protokół": "Protocol",
        "Autołączenie": "Auto-connect",
        "Pełny tunel": "Full tunnel",
        "MacAdBlock używa klienta VPN wbudowanego w macOS. Pełne działanie wymaga podpisanej aplikacji z capability Personal VPN oraz profilu zatwierdzonego przez użytkownika.": "MacAdBlock uses the VPN client built into macOS. Full operation requires a signed app with the Personal VPN capability and a profile approved by the user.",
        "Włączona": "On",
        "Wyłączona": "Off",
        "Ochrona gotowa": "Protection ready",
        "Reklamy i trackery": "Ads and trackers",
        "reguł": "rules",
        "Sekcja hosts": "Hosts section",
        "Reguły zaawansowane": "Advanced rules",
        "Centrum ochrony": "Protection center",
        "Safari i system zabezpieczone w jednym miejscu": "Safari and the system secured in one place",
        "Aktualizuj ochronę": "Update protection",
        "źródeł": "sources",
        "z cache": "from cache",
        "Wymaga aktualizacji": "Needs updating",
        "Włącz Safari": "Enable Safari",
        "Wzmacniamy ochronę": "Strengthening protection",
        "Jesteś chroniony": "You're protected",
        "Włącz ochronę w Safari": "Turn on protection in Safari",
        "Sprawdzanie ochrony": "Checking protection",
        "Wybierz listy": "Choose lists",
        "Ustawienia Safari": "Safari settings",
        "Skonfiguruj hosts": "Set up hosts",
        "Wybierz źródła ochrony": "Choose protection sources",
        "Dokończ konfigurację Safari": "Finish Safari setup",
        "Pobierz pierwsze listy": "Download the first lists",
        "Aktualizujemy ochronę": "Updating protection",
        "Ochrona jest gotowa": "Protection is ready",
        "Kreator dobierze bezpieczny zestaw filtrów.": "The wizard will pick a safe set of filters.",
        "MacAdBlock otworzy ustawienia; zaznacz oba rozszerzenia.": "MacAdBlock will open the settings; tick both extensions.",
        "Jedno kliknięcie pobierze i skompiluje reguły.": "One click downloads and compiles the rules.",
        "Możesz zaktualizować listy albo zmienić zakres ochrony.": "You can update the lists or change the scope of protection.",
        "Otwórz kreator": "Open wizard",
        "Włącz w Safari": "Enable in Safari",
        "Sieć": "Network",
        "Żądania i zasoby": "Requests and resources",
        "Prywatność": "Privacy",
        "Puste pola i banery": "Empty slots and banners",
        "Adresy URL": "URLs",
        "Parametry śledzące": "Tracking parameters",
        "Hosts i DNS": "Hosts and DNS",
        "Warstwy ochrony": "Protection layers",
        "Każda warstwa zatrzymuje inny rodzaj reklamy i śledzenia": "Each layer stops a different kind of ad and tracking",
        "Aktywność filtrów": "Filter activity",
        "Aktualnie skompilowane zasoby ochrony": "Currently compiled protection resources",
        "Listy ochrony": "Protection lists",
        "Szukaj listy, kraju lub kategorii": "Search lists, countries or categories",
        "Tylko aktywne": "Active only",
        "Wyczyść filtry": "Clear filters",
        "Szacowane wpisy": "Estimated entries",
        "Brak pasujących list": "No matching lists",
        "Zmień wyszukiwanie lub wyczyść filtry.": "Change the search or clear the filters.",
        "Zarządzaj grupą": "Manage group",
        "Wyłącz wszystkie": "Disable all",
        "Włącz wszystkie": "Enable all",
        "Wszystkie kategorie": "All categories",
        "Irytujące elementy": "Annoyances",
        "Media społecznościowe": "Social media",
        "Bezpieczeństwo": "Security",
        "Treści i serwisy": "Content and services",
        "Diagnostyka i własne reguły": "Diagnostics and custom rules",
        "Wyjątki działają we wszystkich warstwach: w Safari, w sekcji hosts i w DNS proxy.": "Exceptions apply on every layer: in Safari, in the hosts section and in the DNS proxy.",
        "Ostatnio zablokowane w DNS": "Recently blocked in DNS",
        "Odśwież": "Refresh",
        "Wyczyść": "Clear",
        "Domeny, których zapytania odrzucił DNS proxy. Kliknij domenę, żeby sprawdzić, która lista ją blokuje, albo dodaj ją do wyjątków.": "Domains whose queries the DNS proxy rejected. Click a domain to see which list blocks it, or add it to the exceptions.",
        "Brak wpisów. Dziennik wypełnia się, gdy działa filtrowanie DNS (Ustawienia → DNS).": "No entries. The log fills up while DNS filtering is running (Settings → DNS).",
        "Zezwól": "Allow",
        "Dlaczego strona nie działa": "Why a site doesn't work",
        "Sprawdza pobrane listy i wygenerowane pliki: która lista dotyczy domeny, czy jest w sekcji hosts i ile reguł ukrywania ją obejmuje.": "Checks the downloaded lists and generated files: which list covers the domain, whether it is in the hosts section and how many hiding rules apply to it.",
        "np. sklep.example.com": "e.g. shop.example.com",
        "Sprawdź": "Check",
        "Usuń wyjątek": "Remove exception",
        "Dodaj wyjątek": "Add exception",
        "Domena jest na liście wyjątków — ochrona jej nie dotyczy.": "The domain is on the exceptions list — protection doesn't apply to it.",
        "Żadna włączona reguła nie dotyczy tej domeny. Problem leży poza MacAdBlock.": "No enabled rule applies to this domain. The problem lies outside MacAdBlock.",
        "Domena jest blokowana na poziomie systemu": "The domain is blocked at the system level",
        "Brak wpisu": "No entry",
        "Reguły ukrywania": "Hiding rules",
        "Listy z regułą": "Lists with a rule",
        "Przykładowe reguły": "Sample rules",
        "Strony bez blokowania": "Sites without blocking",
        "np. mojbank.pl": "e.g. mybank.com",
        "Lista jest pusta. Wyjątki dodane w popupie Safari pojawią się tutaj automatycznie.": "The list is empty. Exceptions added in the Safari popup appear here automatically.",
        "Usuń": "Remove",
        "Własne reguły": "Custom rules",
        "Składnia Adblock Plus, jedna reguła w wierszu. Elementy wskazane pickerem w Safari dopisują się tutaj same.": "Adblock Plus syntax, one rule per line. Elements chosen with the Safari picker are added here automatically.",
        "Własne listy": "Custom lists",
        "Lista domen": "Domain list",
        "Dodaj listę": "Add list",
        "Limit reguł Safari": "Safari rule limit",
        "Limit reguł Content Blockera": "Content Blocker rule limit",
        "Safari odrzuca całą listę po przekroczeniu limitu. Gdy tak się stanie, MacAdBlock sam zmniejsza limit i kompiluje reguły ponownie.": "Safari rejects the whole list when the limit is exceeded. When that happens, MacAdBlock lowers the limit and recompiles the rules by itself.",
        "Eksportuj konfigurację": "Export configuration",
        "Wczytaj konfigurację": "Import configuration",
        "Helper hosts jest niedostępny. Zarejestruj go i zatwierdź w Ustawieniach systemowych.": "The hosts helper is unavailable. Register it and approve it in System Settings.",
        "Helper odrzucił operację.": "The helper rejected the operation.",
        "Nie udało się uruchomić helpera z uprawnieniami administratora.": "Could not start the helper with administrator privileges.",
        "Ochrona całego Maca": "Protection for the whole Mac",
        "Blokuje znane domeny reklamowe i śledzące także poza Safari.": "Blocks known advertising and tracking domains outside Safari too.",
        "Działa": "Working",
        "Uprzywilejowany helper": "Privileged helper",
        "Helper modyfikuje wyłącznie oznaczoną sekcję MacAdBlock, wykonuje backup i zapisuje plik atomowo.": "The helper only modifies the marked MacAdBlock section, makes a backup and writes the file atomically.",
        "Napraw helper": "Repair helper",
        "Skonfiguruj helper": "Set up helper",
        "Rzeczy logowania": "Login Items",
        "Zarządzana sekcja /etc/hosts": "Managed /etc/hosts section",
        "Odświeżaj automatycznie razem z listami": "Refresh automatically with the lists",
        "Usuń sekcję MacAdBlock": "Remove MacAdBlock section",
        "Działa poprawnie": "Working correctly",
        "Nie odpowiada": "Not responding",
        "Gotowe do użycia": "Ready to use",
        "Wymagany jeden krok": "One step required",
        "Możesz zastosować listę domen poniżej.": "You can apply the domain list below.",
        "Zatwierdź MacAdBlock w Rzeczach logowania macOS.": "Approve MacAdBlock in macOS Login Items.",
        "Uruchom aplikację z folderu Aplikacje.": "Run the app from the Applications folder.",
        "Zainstaluj i aktywuj bezpieczny helper systemowy.": "Install and activate the secure system helper.",
        "Wymaga zgody": "Needs approval",
        "Niedostępny": "Unavailable",
        "Najpierw zaktualizuj listy filtrów.": "Update the filter lists first.",
        "Test uruchomienia helpera nie powiódł się. Użyj przycisku Napraw helper.": "The helper start-up test failed. Use the Repair helper button.",
        "Tryb lokalny jest gotowy; macOS poprosi o hasło administratora przy zmianach.": "Local mode is ready; macOS will ask for an administrator password when making changes.",
        "Połączenie XPC z uprzywilejowanym helperem odpowiada poprawnie.": "The XPC connection to the privileged helper is responding correctly.",
        "Aktualizuj filtry": "Update filters",
        "Otwórz kreator konfiguracji": "Open setup wizard",
        "Otwórz rozszerzenia Safari": "Open Safari extensions",
        "Sprawdź helper hosts": "Check hosts helper",
        "Sprawdź aktualizacje aplikacji": "Check for app updates",
        "Eksportuj konfigurację…": "Export configuration…",
        "Wczytaj konfigurację…": "Import configuration…",
        "Wyczyść statystyki": "Clear statistics",
        "Diagnostyka i własne reguły…": "Diagnostics and custom rules…",
        "Włochy": "Italy",
        "Konfiguracja ochrony": "Protection setup",
        "Włącz ochronę": "Turn on protection",
        "Jak mocno blokować?": "How strongly to block?",
        "W każdej chwili zmienisz pojedyncze listy.": "You can change individual lists at any time.",
        "wpisów": "entries",
        "Wybierz kraje": "Choose countries",
        "Listy globalne są zawsze aktywne. Dodaj języki stron, które odwiedzasz.": "Global lists are always active. Add the languages of the sites you visit.",
        "Kategorie ochrony": "Protection categories",
        "Ochrona systemowa hosts": "System-wide hosts protection",
        "Banery cookies, popupy i irytujące elementy": "Cookie banners, popups and annoying elements",
        "Przyciski i widżety mediów społecznościowych": "Social media buttons and widgets",
        "Szacowana ochrona": "Estimated protection",
        "Obejmuje Safari oraz połączenia całego systemu.": "Covers Safari and system-wide connections.",
        "Obejmuje tylko strony otwierane w Safari.": "Covers only pages opened in Safari.",
        "Ochrona aktywna": "Protection active",
        "Ochrona wyłączona": "Protection off",
        "Aktualizowanie list…": "Updating lists…",
        "Rozszerzenia Safari": "Safari extensions",
        "Aktualizuj listy": "Update lists",
        "Otwórz MacAdBlock": "Open MacAdBlock",
        "Zakończ": "Quit",
        "Niedostępna": "Unavailable",
        "Ogólne": "General",
        "Podstawowe zachowanie MacAdBlock": "Basic MacAdBlock behavior",
        "Wygląd": "Appearance",
        "Uruchamiaj po zalogowaniu": "Launch at login",
        "MacAdBlock uruchomi ochronę razem z systemem.": "MacAdBlock will start protection together with the system.",
        "Automatycznie stosuj listy hosts": "Apply hosts lists automatically",
        "Po aktualizacji helper bezpiecznie odświeży zarządzaną sekcję /etc/hosts.": "After an update the helper safely refreshes the managed /etc/hosts section.",
        "Automatyczne aktualizacje": "Automatic updates",
        "Wyłączone": "Off",
        "Co 6 godzin": "Every 6 hours",
        "Co 12 godzin": "Every 12 hours",
        "Co tydzień": "Weekly",
        "Uruchom kreator konfiguracji": "Run the setup wizard",
        "Ponownie wybierz profil, kraje i kategorie.": "Choose the profile, countries and categories again.",
        "Kategorie list reklam i elementów stron": "Ad list and page element categories",
        "Podstawowe blokowanie reklam": "Basic ad blocking",
        "Trackery i analityka": "Trackers and analytics",
        "Popupy, cookies i irytujące elementy": "Popups, cookies and annoying elements",
        "Widżety mediów społecznościowych": "Social media widgets",
        "Aktualizuj wszystkie aktywne listy": "Update all active lists",
        "Pobierz najnowsze wersje i przeładuj Safari.": "Download the latest versions and reload Safari.",
        "Opcjonalny moduł Network Extension": "Optional Network Extension module",
        "Preferowany dostawca": "Preferred provider",
        "Włącz filtrowanie DNS": "Turn on DNS filtering",
        "Blokuje domeny z aktywnych list dla wszystkich aplikacji.": "Blocks domains from active lists for all apps.",
        "Stan DNS Proxy": "DNS Proxy status",
        "Szyfruj DNS (DNS-over-HTTPS)": "Encrypt DNS (DNS-over-HTTPS)",
        "Zapytania DNS całego systemu idą szyfrowanym kanałem do wybranego dostawcy, więc sieć ani dostawca internetu ich nie podejrzy.": "System-wide DNS queries go through an encrypted channel to the chosen provider, so neither the network nor your internet provider can see them.",
        "Stan szyfrowanego DNS": "Encrypted DNS status",
        "DoH działa niezależnie od filtrowania DNS powyżej. AdGuard DNS dodatkowo blokuje reklamy po stronie serwera. Szyfrowany DNS wymaga podpisanej aplikacji z uprawnieniem Network Extensions (DNS Settings).": "DoH works independently of the DNS filtering above. AdGuard DNS additionally blocks ads on the server side. Encrypted DNS requires a signed app with the Network Extensions (DNS Settings) entitlement.",
        "DNS Proxy wymaga podpisanego targetu DNSProxy i capability Network Extensions. Wybrany dostawca otrzymuje zapytania DNS; ustawienie Systemowy pozostawia DNS bez zmian.": "DNS Proxy requires a signed DNSProxy target and the Network Extensions capability. The selected provider receives DNS queries; the System setting leaves DNS unchanged.",
        "Ogranicz śledzenie i elementy profilujące": "Limit tracking and profiling elements",
        "Ochrona przed śledzeniem": "Tracking protection",
        "Blokowanie widżetów społecznościowych": "Blocking social widgets",
        "Usuwanie komunikatów i nakładek": "Removing notices and overlays",
        "Prywatny tunel IKEv2 obsługiwany bezpośrednio przez macOS": "Private IKEv2 tunnel handled directly by macOS",
        "Połączono przez": "Connected via",
        "Skonfiguruj operatora i serwer": "Set up the operator and server",
        "Serwer i konto": "Server and account",
        "Inny serwer z konta…": "Another server from your account…",
        "Identyfikator certyfikatu serwera": "Server certificate identifier",
        "Użytkownik": "User",
        "Nazwa użytkownika IKEv2": "IKEv2 username",
        "Hasło": "Password",
        "Pozostaw puste, aby zachować": "Leave empty to keep",
        "Hasło IKEv2": "IKEv2 password",
        "Adres serwera i Remote ID są uzupełniane automatycznie. Login i hasło operatora podajesz raz — hasło zostaje w Pęku kluczy.": "The server address and Remote ID are filled in automatically. You enter the operator's login and password once — the password stays in the Keychain.",
        "Automatyczne łączenie": "Automatic connection",
        "Uruchamiaj VPN": "Start VPN",
        "Zaufane sieci Wi‑Fi, oddzielone przecinkami": "Trusted Wi‑Fi networks, separated by commas",
        "Profil kryptograficzny": "Cryptographic profile",
        "Wymusza prowadzenie całego ruchu internetowego przez VPN.": "Forces all internet traffic through the VPN.",
        "Dostęp do sieci lokalnej": "Local network access",
        "Pozwala nadal korzystać z drukarek, NAS i innych urządzeń LAN.": "Keeps printers, NAS and other LAN devices reachable.",
        "Nie rozłączaj podczas uśpienia": "Stay connected during sleep",
        "Po wybudzeniu macOS spróbuje utrzymać lub odtworzyć bezpieczny tunel.": "After waking, macOS tries to keep or restore the secure tunnel.",
        "Blokuj przekierowanie serwera": "Block server redirect",
        "Nie pozwala serwerowi IKEv2 przenieść połączenia na inny adres.": "Doesn't let the IKEv2 server move the connection to another address.",
        "Bezpieczeństwo i trasy": "Security and routes",
        "Zapisz profil": "Save profile",
        "Zapisz i połącz": "Save and connect",
        "Usuń profil": "Delete profile",
        "Nie udało się wykonać operacji": "The operation failed",
        "Ostatnie rozłączenie": "Last disconnection",
        "Gotowe pozycje to oficjalnie udokumentowane adresy Surfshark i hide.me — MacAdBlock nie uruchamia własnej sieci VPN. Operator nadal wymaga aktywnego konta i danych IKEv2. Hasło trafia do Pęku kluczy, a profil wymaga podpisanej aplikacji z capability Personal VPN i zatwierdzenia przez macOS.": "The ready-made entries are officially documented Surfshark and hide.me addresses — MacAdBlock doesn't run its own VPN network. The operator still requires an active account and IKEv2 credentials. The password goes to the Keychain, and the profile requires a signed app with the Personal VPN capability and macOS approval.",
        "Phishing, oszustwa i złośliwe domeny": "Phishing, scams and malicious domains",
        "Ochrona przed phishingiem i oszustwami": "Protection against phishing and scams",
        "Listy domen malware": "Malware domain lists",
        "MacAdBlock blokuje znane domeny, ale nie zastępuje programu antywirusowego.": "MacAdBlock blocks known domains but doesn't replace antivirus software.",
        "Rozszerzenia i reguły Content Blocker": "Extensions and Content Blocker rules",
        "Włączony": "Enabled",
        "Wymaga włączenia": "Needs enabling",
        "Włączone": "Enabled",
        "Pełna ochrona Safari": "Full Safari protection",
        "Reguły Content Blocker": "Content Blocker rules",
        "Reguły Web Extension": "Web Extension rules",
        "Dokończ włączenie w Safari": "Finish enabling in Safari",
        "MacAdBlock otworzy właściwy panel. Zaznacz oba rozszerzenia i zezwól na dostęp do witryn.": "MacAdBlock will open the right panel. Tick both extensions and allow access to websites.",
        "Rozszerzenia są już dołączone do aplikacji i instalują się razem z nią. Ze względów bezpieczeństwa macOS nie pozwala aplikacji samodzielnie zaznaczyć zgody w Safari — tę jedną czynność musi wykonać użytkownik.": "The extensions are already bundled with the app and install together with it. For security reasons macOS doesn't let an app tick the consent in Safari by itself — the user has to do this one step.",
        "Sieć i hosts": "Network and hosts",
        "Ochrona wszystkich aplikacji przez /etc/hosts": "Protecting all apps through /etc/hosts",
        "Helper systemowy": "System helper",
        "Sekcja MacAdBlock w hosts": "MacAdBlock section in hosts",
        "Zablokowane domeny": "Blocked domains",
        "Zastosuj hosts": "Apply hosts",
        "Usuń sekcję hosts": "Remove hosts section",
        "Sprawdź helper": "Check helper",
        "Diagnostyka i operacje konserwacyjne": "Diagnostics and maintenance",
        "Wersja MacAdBlock": "MacAdBlock version",
        "Integracje systemowe": "System integrations",
        "Aktualizuj ochronę teraz": "Update protection now",
        "Usuwa zapisane liczniki aktualizacji i reguł.": "Removes stored update and rule counters.",
        "Wyłączony": "Off",
        "Wybierz dostawcę DNS": "Choose a DNS provider",
        "Wymaga podpisania i capability Network Extension": "Requires signing and the Network Extension capability",
        "Zatwierdź w Ustawieniach systemowych → Sieć → Filtry i serwery proxy DNS": "Approve in System Settings → Network → Filters and DNS proxies",
        "Wymaga podpisania i uprawnienia Network Extension": "Requires signing and the Network Extension entitlement",
        "Systemowy": "System",
        "Ciemny": "Dark",
        "Jasny": "Light",
        "Automatyczny": "Automatic",
        "Ustawienia": "Settings",
        "Ochrona": "Protection",
        "Filtry": "Filters",
        "Trasa": "Route",
        "Serwer": "Server",
        "Zaawansowane": "Advanced",
        "Aktywność ochrony": "Protection activity",
        "Podsumowanie skompilowanych reguł i źródeł": "Summary of compiled rules and sources",
        "Wszystkie reguły": "All rules",
        "Domeny hosts": "Hosts domains",
        "Aktywne źródła": "Active sources",
        "Pominięte bezpiecznie": "Safely skipped",
        "Rozkład ochrony": "Protection breakdown",
        "Pominięte reguły nie są zgodne z bezpiecznymi API Safari.": "Skipped rules aren't compatible with Safari's safe APIs.",
        "Sieciowe": "Network",
        "Kosmetyczne": "Cosmetic",
        "Domeny": "Domains",
        "Rozszerzenie": "Extension",
        "Aktualizacja": "Update",
        "Aktualizuj": "Update",
        "Trackery": "Trackers",
        "Liczba": "Count",
        "Rodzaj": "Type",
        "Kategoria": "Category",
        "Reklamy": "Ads",
        "Regionalne": "Regional",
        "Wszystkie": "All",
        "Brak": "None",
        "Scriptlety": "Scriptlets",
        "Zapisz": "Save",
        "Nazwa": "Name",
        "Skonfiguruj": "Set up",
        "Konfiguracja": "Configuration",
        "Nieznany": "Unknown",
        "Nieaktualne": "Outdated",
        "Nieaktywne": "Inactive",
        "Wstecz": "Back",
        "Aktywna": "Active",
        "Gotowa": "Ready",
        "Nieznana": "Unknown",
        "Lokalizacja": "Location",
        "Sprawdzanie": "Checking",
        "Nieaktywna": "Inactive",
        "Aktywny": "Active",
        "Zgodny": "Compatible",
        "Nowoczesny": "Modern",
        "Wzmocniony": "Hardened",
        "Nieskonfigurowany": "Not configured",
        "Własny IKEv2": "Custom IKEv2",
        "Adres serwera, np. vpn.example.com": "Server address, e.g. vpn.example.com",
        "Hostname lokalizacji z konta Surfshark": "Location hostname from your Surfshark account",
        "Serwer z panelu hide.me, np. nl.hide.me": "Server from the hide.me panel, e.g. nl.hide.me",
        "Użyj danych administratora własnego serwera IKEv2. Serwer musi obsługiwać uwierzytelnianie EAP nazwą użytkownika i hasłem.": "Use the administrator details of your own IKEv2 server. The server must support EAP authentication with a username and password.",
        "Wybierz gotową lokalizację poniżej. Surfshark nadal wymaga osobnych danych ręcznej konfiguracji IKEv2 oraz własnego certyfikatu; wpisujesz je tylko przy pierwszym zapisie.": "Choose a ready-made location below. Surfshark still requires separate manual IKEv2 credentials and its own certificate; you enter them only on the first save.",
        "Wybierz gotową lokalizację poniżej. Dane konta IKEv2 wpisujesz tylko przy pierwszym zapisie, a identyfikator zdalny zostanie ustawiony automatycznie.": "Choose a ready-made location below. You enter the IKEv2 account details only on the first save, and the remote ID is set automatically.",
        "Francja — Bordeaux": "France — Bordeaux",
        "Konto Surfshark": "Surfshark account",
        "Niderlandy — bezpłatny": "Netherlands — free",
        "Konto bezpłatne": "Free account",
        "Konto Premium": "Premium account",
        "USA — serwer 1": "USA — server 1",
        "Ustawienia systemowe Apple — najlepsza zgodność z operatorami.": "Apple's system defaults — best compatibility with operators.",
        "AES-256-GCM, SHA-384 i grupa DH 20. Zalecany dla własnego serwera.": "AES-256-GCM, SHA-384 and DH group 20. Recommended for your own server.",
        "AES-256-GCM, SHA-512 i grupa DH 21. Może nie działać ze starszym serwerem.": "AES-256-GCM, SHA-512 and DH group 21. May not work with an older server.",
        "Ręcznie": "Manually",
        "Każda sieć": "Every network",
        "Poza zaufanym Wi‑Fi": "Outside trusted Wi‑Fi",
        "Wpisz adres serwera, identyfikator zdalny i nazwę użytkownika.": "Enter the server address, remote ID and username.",
        "Wpisz poprawny hostname lub adres IP serwera, bez protokołu, ścieżki, portu i spacji.": "Enter a valid hostname or IP address, without protocol, path, port or spaces.",
        "Identyfikator zdalny nie może zawierać protokołu, ścieżki ani spacji.": "The remote ID can't contain a protocol, path or spaces.",
        "Wpisz hasło do serwera VPN.": "Enter the VPN server password.",
        "Profil wymaga naprawy": "The profile needs repair",
        "Rozłączony": "Disconnected",
        "Łączenie…": "Connecting…",
        "Połączony": "Connected",
        "Ponowne łączenie…": "Reconnecting…",
        "Rozłączanie…": "Disconnecting…",
        "Nieznany stan": "Unknown state",
        "Nieprawidłowy adres serwera.": "Invalid server address.",
        "Sieć lokalna jest niedostępna.": "The local network is unavailable.",
        "Połączenie z internetem jest niedostępne.": "The internet connection is unavailable.",
        "Nie udało się odnaleźć adresu serwera.": "Could not find the server address.",
        "Serwer VPN nie odpowiada.": "The VPN server is not responding.",
        "Serwer VPN przestał działać.": "The VPN server stopped working.",
        "Serwer odrzucił nazwę użytkownika lub hasło.": "The server rejected the username or password.",
        "Serwer nie zaakceptował ustawień szyfrowania. Wybierz profil Zgodny.": "The server didn't accept the encryption settings. Choose the Compatible profile.",
        "Serwer zakończył połączenie.": "The server ended the connection.",
        "Certyfikat serwera jest nieprawidłowy lub nieważny.": "The server certificate is invalid or expired.",
        "VPN wymaga podpisania aplikacji i capability Personal VPN. Po zapisaniu zaakceptuj profil w oknie macOS.": "VPN requires a signed app with the Personal VPN capability. After saving, accept the profile in the macOS dialog.",
    ]
}
