import Foundation

public enum FilterCatalog {
    public static let all: [FilterSource] = [
        source("easylist", "EasyList", "https://easylist.to/easylist/easylist.txt", .adblock, .ads, true, "https://easylist.to/", "INT", "Globalne", 85_000),
        source("easyprivacy", "EasyPrivacy", "https://easylist.to/easylist/easyprivacy.txt", .adblock, .privacy, true, "https://easylist.to/", "INT", "Globalne", 55_000),
        source("fanboy-annoyance", "Fanboy Annoyances", "https://easylist.to/easylist/fanboy-annoyance.txt", .adblock, .annoyances, false, "https://easylist.to/", "INT", "Globalne", 35_000),
        source("fanboy-social", "Fanboy Social", "https://easylist.to/easylist/fanboy-social.txt", .adblock, .social, false, "https://easylist.to/", "INT", "Globalne", 20_000),
        source("easylist-cookies", "EasyList Cookie Notices", "https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-cookies.txt", .adblock, .annoyances, false, "https://github.com/easylist/easylist", "INT", "Globalne", 45_000),
        source("easylist-newsletters", "EasyList Newsletter Notices", "https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-newsletters.txt", .adblock, .annoyances, false, "https://github.com/easylist/easylist", "INT", "Globalne", 8_000),
        source("easylist-notifications", "EasyList Notifications", "https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-notifications.txt", .adblock, .annoyances, false, "https://github.com/easylist/easylist", "INT", "Globalne", 5_000),
        source("adguard-base", "AdGuard Base", "https://filters.adtidy.org/extension/ublock/filters/2.txt", .adblock, .ads, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 80_000),
        source("adguard-tracking", "AdGuard Tracking Protection", "https://filters.adtidy.org/extension/ublock/filters/3.txt", .adblock, .privacy, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 45_000),
        source("adguard-social", "AdGuard Social Media", "https://filters.adtidy.org/extension/ublock/filters/4.txt", .adblock, .social, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 20_000),
        source("adguard-annoyances", "AdGuard Annoyances", "https://filters.adtidy.org/extension/ublock/filters/14.txt", .adblock, .annoyances, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 65_000),
        source("adguard-url-tracking", "AdGuard URL Tracking", "https://filters.adtidy.org/extension/ublock/filters/17.txt", .adblock, .privacy, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 2_000),
        source("ublock-ads", "uBlock Filters – Ads", "https://ublockorigin.github.io/uAssetsCDN/filters/filters.min.txt", .adblock, .ads, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 40_000),
        source("ublock-privacy", "uBlock Filters – Privacy", "https://ublockorigin.github.io/uAssetsCDN/filters/privacy.min.txt", .adblock, .privacy, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 8_000),
        source("ublock-quick-fixes", "uBlock Filters – Quick Fixes", "https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.txt", .adblock, .ads, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 3_000),
        source("ublock-badware", "uBlock Filters – Badware", "https://ublockorigin.github.io/uAssetsCDN/filters/badware.txt", .adblock, .malware, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 5_000),
        source("polish", "Oficjalne Polskie Filtry", "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt", .adblock, .regional, true, "https://github.com/MajkiIT/polish-ads-filter", "PL", "Polska", 18_000),
        source("easylist-germany", "EasyList Germany", "https://easylist.to/easylistgermany/easylistgermany.txt", .adblock, .regional, false, "https://easylist.to/", "DE", "Niemcy", 12_000),
        source("liste-fr", "Liste FR", "https://easylist-downloads.adblockplus.org/liste_fr.txt", .adblock, .regional, false, "https://easylist.to/", "FR", "Francja", 18_000),
        source("easylist-italy", "EasyList Italy", "https://easylist-downloads.adblockplus.org/easylistitaly.txt", .adblock, .regional, false, "https://easylist.to/", "IT", "Włochy", 11_000),
        source("easylist-spanish", "EasyList Spanish", "https://easylist-downloads.adblockplus.org/easylistspanish.txt", .adblock, .regional, false, "https://easylist.to/", "ES", "Hiszpania", 9_000),
        source("easylist-dutch", "EasyList Dutch", "https://easylist-downloads.adblockplus.org/easylistdutch.txt", .adblock, .regional, false, "https://easylist.to/", "NL", "Niderlandy", 8_000),
        source("stevenblack", "StevenBlack Unified", "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts", .hosts, .ads, true, "https://github.com/StevenBlack/hosts", "INT", "Globalne", 80_000),
        source("adaway", "AdAway Hosts", "https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt", .hosts, .ads, false, "https://github.com/AdAway/adaway.github.io", "INT", "Globalne", 8_500),
        source("peter-lowe", "Peter Lowe Hosts", "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext", .hosts, .ads, false, "https://pgl.yoyo.org/adservers/", "INT", "Globalne", 3_500),
        source("hagezi-pro", "HaGeZi Multi PRO", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists-legacy@latest/hosts/pro.txt", .hosts, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 220_000),
        source("stevenblack-fakenews", "StevenBlack Fake News", "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-only/hosts", .hosts, .security, false, "https://github.com/StevenBlack/hosts", "INT", "Globalne", 2_200),
        source("stevenblack-gambling", "StevenBlack Gambling", "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts", .hosts, .annoyances, false, "https://github.com/StevenBlack/hosts", "INT", "Globalne", 4_000),
        source("cert-pl", "CERT Polska", "https://hole.cert.pl/domains/v2/domains.txt", .domains, .security, true, "https://cert.pl/lista-ostrzezen/", "PL", "Polska", 120_000),
        source("hagezi-light", "HaGeZi Light", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/light-onlydomains.txt", .domains, .ads, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 60_000, extra: true),
        source("hagezi-multi", "HaGeZi Multi NORMAL", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/multi-onlydomains.txt", .domains, .ads, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 110_000, extra: true),
        source("hagezi-pro-domains", "HaGeZi Multi PRO (domeny)", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro-onlydomains.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 180_000, extra: true),
        source("hagezi-pro-plus", "HaGeZi Multi PRO++", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.plus-onlydomains.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 250_000, extra: true),
        source("hagezi-ultimate", "HaGeZi Multi ULTIMATE", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate-onlydomains.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 400_000, extra: true),
        source("hagezi-tif", "HaGeZi Threat Intelligence Feeds", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif-onlydomains.txt", .domains, .malware, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 500_000, extra: true),
        source("hagezi-fake", "HaGeZi Fake (oszustwa)", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/fake-onlydomains.txt", .domains, .security, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 20_000, extra: true),
        source("hagezi-popupads", "HaGeZi Pop-Up Ads", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads-onlydomains.txt", .domains, .annoyances, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 60_000, extra: true),
        source("hagezi-gambling", "HaGeZi Gambling", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/gambling-onlydomains.txt", .domains, .content, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 100_000, extra: true),
        source("hagezi-nsfw", "HaGeZi NSFW (treści dla dorosłych)", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nsfw-onlydomains.txt", .domains, .content, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 60_000, extra: true),
        source("hagezi-native-tiktok", "HaGeZi Native Tracker: TikTok", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/native.tiktok-onlydomains.txt", .domains, .social, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 300, extra: true),
        source("hagezi-native-samsung", "HaGeZi Native Tracker: Samsung", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/native.samsung-onlydomains.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 200, extra: true),
        source("hagezi-native-apple", "HaGeZi Native Tracker: Apple", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/native.apple.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 100, extra: true),
        source("hagezi-native-microsoft", "HaGeZi Native Tracker: Windows/Office", "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/native.winoffice-onlydomains.txt", .domains, .privacy, false, "https://github.com/hagezi/dns-blocklists", "INT", "Globalne", 200, extra: true),
        source("stevenblack-porn", "StevenBlack Porn", "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts", .hosts, .content, false, "https://github.com/StevenBlack/hosts", "INT", "Globalne", 75_000, extra: true),
        source("stevenblack-social", "StevenBlack Social", "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social-only/hosts", .hosts, .content, false, "https://github.com/StevenBlack/hosts", "INT", "Globalne", 500, extra: true),
        source("kadhosts", "KADhosts", "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt", .hosts, .regional, false, "https://github.com/PolishFiltersTeam/KADhosts", "PL", "Polska", 25_000, extra: true),
        source("majkiit-hostfile", "MajkiIT Polish Adblock Hostfile", "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt", .hosts, .regional, false, "https://github.com/MajkiIT/polish-ads-filter", "PL", "Polska", 10_000, extra: true),
        source("urlhaus-hosts", "URLhaus Malware Hosts", "https://urlhaus.abuse.ch/downloads/hostfile/", .hosts, .malware, false, "https://urlhaus.abuse.ch/", "INT", "Globalne", 1_000, extra: true),
        source("phishing-army", "Phishing Army", "https://phishing.army/download/phishing_army_blocklist.txt", .domains, .security, false, "https://phishing.army/", "INT", "Globalne", 150_000, extra: true),
        source("frogeye-firstparty", "Frogeye First-Party Trackers", "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt", .hosts, .privacy, false, "https://hostfiles.frogeye.fr/", "INT", "Globalne", 30_000, extra: true),
        source("anudeep-adservers", "Anudeep AdServers", "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt", .hosts, .ads, false, "https://github.com/anudeepND/blacklist", "INT", "Globalne", 40_000, extra: true),
        source("1hosts-lite", "1Hosts Lite", "https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt", .domains, .ads, false, "https://github.com/badmojr/1Hosts", "INT", "Globalne", 60_000, extra: true),
        source("nocoin", "NoCoin (kopanie kryptowalut)", "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt", .hosts, .malware, false, "https://github.com/hoshsadiq/adblock-nocoin-list", "INT", "Globalne", 300, extra: true),
        source("smarttv", "Smart-TV Blocklist", "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt", .domains, .privacy, false, "https://github.com/Perflyst/PiHoleBlocklist", "INT", "Globalne", 300, extra: true),
        source("blp-ads", "Blocklist Project: Ads", "https://blocklistproject.github.io/Lists/ads.txt", .hosts, .ads, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 150_000, extra: true),
        source("blp-tracking", "Blocklist Project: Tracking", "https://blocklistproject.github.io/Lists/tracking.txt", .hosts, .privacy, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 15_000, extra: true),
        source("blp-malware", "Blocklist Project: Malware", "https://blocklistproject.github.io/Lists/malware.txt", .hosts, .malware, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 400_000, extra: true),
        source("blp-phishing", "Blocklist Project: Phishing", "https://blocklistproject.github.io/Lists/phishing.txt", .hosts, .security, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 190_000, extra: true),
        source("blp-scam", "Blocklist Project: Scam", "https://blocklistproject.github.io/Lists/scam.txt", .hosts, .security, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 20_000, extra: true),
        source("blp-ransomware", "Blocklist Project: Ransomware", "https://blocklistproject.github.io/Lists/ransomware.txt", .hosts, .malware, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 20_000, extra: true),
        source("blp-crypto", "Blocklist Project: Crypto", "https://blocklistproject.github.io/Lists/crypto.txt", .hosts, .malware, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 20_000, extra: true),
        source("blp-porn", "Blocklist Project: Porn", "https://blocklistproject.github.io/Lists/porn.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 500_000, extra: true),
        source("blp-gambling", "Blocklist Project: Gambling", "https://blocklistproject.github.io/Lists/gambling.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 10_000, extra: true),
        source("blp-drugs", "Blocklist Project: Drugs", "https://blocklistproject.github.io/Lists/drugs.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 10_000, extra: true),
        source("blp-piracy", "Blocklist Project: Piracy", "https://blocklistproject.github.io/Lists/piracy.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 2_000, extra: true),
        source("blp-torrent", "Blocklist Project: Torrent", "https://blocklistproject.github.io/Lists/torrent.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 1_000, extra: true),
        source("blp-facebook", "Blocklist Project: Facebook", "https://blocklistproject.github.io/Lists/facebook.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 150, extra: true),
        source("blp-tiktok", "Blocklist Project: TikTok", "https://blocklistproject.github.io/Lists/tiktok.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 50, extra: true),
        source("blp-youtube", "Blocklist Project: YouTube", "https://blocklistproject.github.io/Lists/youtube.txt", .hosts, .content, false, "https://github.com/blocklistproject/Lists", "INT", "Globalne", 50, extra: true),
        source("adguard-dns", "AdGuard DNS Filter", "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt", .adblock, .ads, false, "https://github.com/AdguardTeam/AdGuardSDNSFilter", "INT", "Globalne", 50_000, extra: true),
        source("adguard-mobile", "AdGuard Mobile Ads", "https://filters.adtidy.org/extension/ublock/filters/11.txt", .adblock, .ads, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 9_000, extra: true),
        source("adguard-popups", "AdGuard Popups", "https://filters.adtidy.org/extension/ublock/filters/19.txt", .adblock, .annoyances, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 1_000, extra: true),
        source("adguard-widgets", "AdGuard Other Annoyances: Widgets", "https://filters.adtidy.org/extension/ublock/filters/22.txt", .adblock, .annoyances, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 5_000, extra: true),
        source("adguard-cookies", "AdGuard Cookie Notices", "https://filters.adtidy.org/extension/ublock/filters/18.txt", .adblock, .annoyances, false, "https://github.com/AdguardTeam/AdguardFilters", "INT", "Globalne", 10_000, extra: true),
        source("adguard-german", "AdGuard German", "https://filters.adtidy.org/extension/ublock/filters/6.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "DE", "Niemcy", 5_000, extra: true),
        source("adguard-french", "AdGuard French", "https://filters.adtidy.org/extension/ublock/filters/16.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "FR", "Francja", 3_000, extra: true),
        source("adguard-spanish", "AdGuard Spanish/Portuguese", "https://filters.adtidy.org/extension/ublock/filters/9.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "ES", "Hiszpania", 3_000, extra: true),
        source("adguard-russian", "AdGuard Russian", "https://filters.adtidy.org/extension/ublock/filters/1.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "RU", "Rosja", 30_000, extra: true),
        source("adguard-turkish", "AdGuard Turkish", "https://filters.adtidy.org/extension/ublock/filters/13.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "TR", "Turcja", 3_000, extra: true),
        source("adguard-japanese", "AdGuard Japanese", "https://filters.adtidy.org/extension/ublock/filters/7.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "JP", "Japonia", 2_000, extra: true),
        source("adguard-dutch", "AdGuard Dutch", "https://filters.adtidy.org/extension/ublock/filters/8.txt", .adblock, .regional, false, "https://github.com/AdguardTeam/AdguardFilters", "NL", "Holandia", 2_000, extra: true),
        source("ublock-unbreak", "uBlock filters – Unbreak", "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt", .adblock, .ads, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 4_000, extra: true),
        source("ublock-resource-abuse", "uBlock filters – Resource Abuse", "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt", .adblock, .malware, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 300, extra: true),
        source("ublock-annoyances", "uBlock filters – Annoyances", "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt", .adblock, .annoyances, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 30_000, extra: true),
        source("ublock-cookies", "uBlock filters – Cookie Notices", "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-cookies.txt", .adblock, .annoyances, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 20_000, extra: true),
        source("ublock-annoyances-others", "uBlock filters – Other Annoyances", "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-others.txt", .adblock, .annoyances, false, "https://github.com/uBlockOrigin/uAssets", "INT", "Globalne", 10_000, extra: true),
        source("anti-adblock-killer-warning", "Adblock Warning Removal List", "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt", .adblock, .annoyances, false, "https://easylist.to/", "INT", "Globalne", 3_000, extra: true),
        source("easylist-czech", "EasyList Czech and Slovak", "https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt", .adblock, .regional, false, "https://github.com/tomasko126/easylistczechandslovak", "CZ", "Czechy", 3_000, extra: true),
        source("easylist-portuguese", "EasyList Portuguese", "https://easylist-downloads.adblockplus.org/easylistportuguese.txt", .adblock, .regional, false, "https://easylist.to/", "PT", "Portugalia", 2_000, extra: true),
        source("easylist-china", "EasyList China", "https://easylist-downloads.adblockplus.org/easylistchina.txt", .adblock, .regional, false, "https://easylist.to/", "CN", "Chiny", 3_000, extra: true),
        source("easylist-lithuania", "EasyList Lithuania", "https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt", .adblock, .regional, false, "https://github.com/EasyList-Lithuania/easylist_lithuania", "LT", "Litwa", 1_500, extra: true)

    ]

    private static func source(
        _ id: String,
        _ name: String,
        _ url: String,
        _ format: FilterFormat,
        _ category: FilterCategory,
        _ enabled: Bool,
        _ homepage: String,
        _ countryCode: String,
        _ countryName: String,
        _ estimatedRuleCount: Int,
        extra: Bool = false
    ) -> FilterSource {
        FilterSource(
            id: id,
            name: name,
            url: URL(string: url)!,
            format: format,
            category: category,
            enabledByDefault: enabled,
            homepage: URL(string: homepage)!,
            countryCode: countryCode,
            countryName: countryName,
            estimatedRuleCount: estimatedRuleCount,
            isExtra: extra
        )
    }
}
